server:
  port: 9890

spring:
  application:
    name: menstrual-mate-backend
  
  datasource:
    url: jdbc:mysql://localhost:3306/menstrual_mate?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: menstrual_user
    password: menstrual_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false
  
  sql:
    init:
      data-locations: classpath:data.sql
      mode: never
  
  web:
    cors:
      allowed-origins: http://localhost:3000, http://localhost:3001, http://localhost:8080
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS
      allowed-headers: "*"
      allow-credentials: true

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/menstrual_mate?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: menstrual_user
    password: menstrual_pass

logging:
  level:
    com.menstrualmate: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always